version: '3.7'

networks:
  default:
    
    name: kafka

services:

  schema-registry:
      networks:
        default:
      image: confluentinc/cp-schema-registry:latest
      ports:
        - 8081:8081
      environment:
        SCHEMA_REGISTRY_HOST_NAME: test
        SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka-2:9092,kafka-2:9092
        SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
  