---
version: '3.7'

networks:
  default:
    name: kafka

services:
  zk-1:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: "zk1:12181:13888;zk2:22181:23888;zk3:32181:33888"
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=*"
    networks:
      default:
        aliases:
          - zk1
    ports:
      - 12181:2181

  zk-2:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: "zk1:12181:13888;zk2:22181:23888;zk3:32181:33888"
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=*"
    networks:
      default:
        aliases:
          - zk2
    ports:
      - 22181:2181

  zk-3:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: "zk1:12181:13888;zk2:22181:23888;zk3:32181:33888"
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=*"
    networks:
      default:
        aliases:
          - zk3
    ports:
      - 32181:2181